name: Build, Compress and Deploy Angular App

on:
  push:
    branches:
      - main

jobs:
  build_and_compress:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18.13.0

    - name: Install Dependencies
      run: npm install

    - name: Print Before jq
      run: |
        echo "Before jq auth_config.json:"
        cat auth_config.json
        echo "Before jq app-settings.json:"
        cat ./src/assets/app-settings/app-settings.json

    - name: Replace config with environment values
      env:
        API_URL: ${{ secrets.API_URL }}
        APP_URL: ${{ secrets.APP_URL }}
        AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID}}
      run: |
        jq --arg auth0ClientId "$AUTH0_CLIENT_ID" --arg apiUri "$API_URL" --arg appUri "$APP_URL" '.clientId |= $auth0ClientId | .apiUri |= $apiUri | .appUri |= $appUri' auth_config.json > auth_config.json.tmp
        mv auth_config.json.tmp auth_config.json
        jq --arg apiUrl "$API_URL" '.apiUrl |= $apiUrl' ./src/assets/app-settings/app-settings.json > app-settings.json.tmp
        mv app-settings.json.tmp ./src/assets/app-settings/app-settings.json

    - name: Print after jq
      run: |
        echo "After jq auth_config.json:"
        cat auth_config.json
        echo "After jq app-settings.json:"
        cat ./src/assets/app-settings/app-settings.json

    - name: Build Angular App
      run: npm run build -- --configuration production

    - name: Install Zip
      run: sudo apt-get install zip

    - name: Create Zip Archive
      run: zip -r angular-app.zip dist/

    - name: copy file via ssh password
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        source: "angular-app.zip"
        target: repos/media-scrapper-client
        overwrite: true

    - name: Deploy app
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{secrets.HOST}} # IP address of the server you wish to ssh into
        username: ${{ secrets.SSH_USERNAME }} # User of the server you want to ssh into
        password: ${{ secrets.SSH_PASSWORD }}
        script: |
          cd repos/media-scrapper-client
          rm -rf built-files
          unzip -o angular-app.zip -d /var/www/media-scrapper-client          
          echo 'Deployment successful to digital ocean' 
